### ISSUE TITLE
generate pivot table missing Name

### ISSUE THREAD

**Issue by maddeezy** [bpocallaghan/generators#7]
Ex:

When I run the generate:migration:pivot foos bars

The migration created is created as:

class  extends Migration
{

(missing the name)

I believe it should be

class  **CreateFooBarPivotTable** extends Migration
{

I don't see that this function is being called anywhere during the pivot migration 

protected function parseName($name)
    {
        $tables = array_map('str_singular', $this->getSortedTableNames());
        $name = implode('', array_map('ucwords', $tables));

        return "Create{$name}PivotTable";
    }

From the:
public function fire()
    {
        $name = $this->qualifyClass($this->getNameInput());
       ......

It looks like it is calling only
/**
     * Empty 'name' argument
     *
     * @return string
     */
    protected function getNameInput()
    {
        //
    }

Which of course will return an empty name

In the meantime, I'll just type that in

Thanks

**Comment by bpocallaghan** [comment]
Hi Erik

Thanks for logging the bug.
Please find the fix with version 4.0.4.

I've also added a few more commands:

`generate:notification NotificationName`
`generate:event EventName`
`generate:listener ListenerName --event=EventName`
`generate:event-listener` (generate the missing events and listeners)

**Comment by maddeezy** [comment]
Sort of fixed (unless my naming convention is wrong)

Example:
generate:migration:pivot foo_bar upload

It creates the name as:

createFoo_BarUploadPivotTable

I believe it should be 
createFooBarUploadPivotTable

I fixed it by doing a str_replace("_", "", ...)

Is it bad practice to use foo_bar as a naming convention?  It is super readable, but not sure it is standard.

**Comment by bpocallaghan** [comment]
Hi Erik

aaah, To be honest, I am not sure - Most of the Migration Pivot code is from Jeffreys' L4 generators package.
I personally use _ in my table names -- user_role

Will add it quick!

**Comment by bpocallaghan** [comment]
Hi Erik

Added new release - 4.0.5

generate:migration:pivot foo bar  -- CreateFooBarPivotTable
generate:migration:pivot foo_bar taz  -- CreateFooBarTazPivotTable

Both should work now

**Comment by maddeezy** [comment]
That was fast!!  Where do we send donations 😀

**Comment by bpocallaghan** [comment]
hahaha.
You are the second person contacting me regarding the package - I need to keep the 2 users happy :)

Please let me know if you have any other suggestions, I personally think the 'custom stubs' are very nice to add your boilerplate. Can easily add views / controllers for the cms and website part.

Let me know if its not resolved :)

**Comment by maddeezy** [comment]
I ended up using your package and then came up with a blade templating system that pulls from the migrations (Schema) and shows all the CRUD dynamically so I never have to return to the views again for basic CRUD stuff...I pass a few parameters like $do_not_display (then they don't show up on the view for index or show)

So yeah, the custom stubs are perfect!!

This package helped me to really standardize everything and reduced the time drastically.

If you're interested in doing any team mentoring (for compensation of course) let me know.

So start LaravelMentoring.com and I'll be your first customer...

**Comment by maddeezy** [comment]
Works perfectly...even using plural forms besides "s" like celebrity becomes celebrities_id in the pivot table.

Excellent
